name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy application
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}

        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem

          ssh -i key.pem -p 2222 -o StrictHostKeyChecking=no romain@$SERVER_IP << 'EOF'

            echo "==> Navigating to project directory..."
            cd /srv/app_agricole/AgriCEN

            echo "==> Fetching and resetting branch to origin/main..."
            git fetch origin
            git reset --hard origin/main
            git log -1
            git status

            echo "==> Checking for changes in Dockerfile or dependencies..."
            if git diff --name-only HEAD~1 HEAD | grep -E 'Dockerfile|requirements.txt'; then
              echo "Changes detected in Dockerfile or requirements.txt. Rebuilding Docker container..."
              docker-compose down
              docker-compose build --no-cache
              docker-compose up -d
            else
              echo "No changes requiring a container rebuild. Restarting application inside container..."
              docker exec flask-leaflet_web_1 kill -HUP 1 || true
            fi

            echo "==> Deployment complete!"
          EOF

          echo "Cleaning up SSH key..."
          rm -f key.pem
